---
AWSTemplateFormatVersion: 2010-09-09
Description: pricing network resources

Parameters:
  cidr:
    Type: String
    Description: VPC's CIDR

  appCidr:
    Description: app VPC cidr
    Type: String

  appSubnetCidr:
    Description: App subnet cidr range
    Type: String

  publicSubnetCidr:
    Description: Public subnet cidr range
    Type: String

Resources:
  igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'

  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref cidr
      InstanceTenancy: default
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  
  vpcIgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref igw
      VpcId: !Ref vpc

  routeTableApp:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-app-rt'

  appSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref vpc
      CidrBlock: !Ref appSubnetCidr
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-app-subnet'

  routeAppSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref appSubnet
      RouteTableId: !Ref routeTableApp

  routeTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref vpc
      Tags:
        - Key: Name
          Value: !Sub 'public-${AWS::StackName}-subnet-rt'

  publicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref vpc
      CidrBlock: !Ref publicSubnetCidr
      Tags:
        - Key: Name
          Value: !Sub 'public-${AWS::StackName}-subnet'

  routePublicSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnet
      RouteTableId: !Ref routeTablePublic

  NATGatewayEIPA:
   Type: AWS::EC2::EIP
   Properties:
      Domain: vpc

  NATGateway:
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId: !GetAtt NATGatewayEIPA.AllocationId
      SubnetId: !Ref publicSubnet

  igwPublicSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref routeTablePublic
      GatewayId: !Ref igw

  routeApp:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref routeTableApp
      NatGatewayId: !Ref NATGateway

  naclApp:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-app'

  naclAppIngressFromInetEph:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref naclApp
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 1024
        To: 65535

  naclAppEgressFromInetEph:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Egress: true
      NetworkAclId: !Ref naclApp
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 443
        To: 443

  naclAssocApp:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref appSubnet
      NetworkAclId: !Ref naclApp

  flowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 365

  flowLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: flowlog-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !GetAtt flowLogGroup.Arn

  flowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt flowLogRole.Arn
      LogGroupName: !Ref flowLogGroup
      ResourceId: !Ref vpc
      ResourceType: VPC
      TrafficType: ALL

  paramVpcID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /network/vpc-id
      Type: String
      Value: !Ref vpc

  paramAppSubnet:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /network/app-subnet
      Type: String
      Value: !Ref appSubnet

  paramAppPublicSubnet:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /network/public-subnet
      Type: String
      Value: !Ref publicSubnet

  paramAppCidr:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /network/appCidr
      Type: String
      Value: !Ref appCidr

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for vpc endpoints
      VpcId: !Ref vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref cidr
          Description: Allow all traffic on port 443 from the VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Allow all traffic on port 443